---
name: Main Build Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  markdown-lint:
    name: Markdown Lint
    uses: ikostan/intro_to_godot_by_zenva/.github/workflows/markdown-lint.yml@master
  yaml-lint:
    name: YAML Lint
    uses: ikostan/intro_to_godot_by_zenva/.github/workflows/yamllint.yml@master
